name: build

on:
  workflow_dispatch:
    inputs:
      gitref:
        description: 'Repository reference'
        type: string
        default: 'master'
        required: true
      upstream:
        description: 'Upstream repository'
        type: choice
        default: 'https://gitlab.com/qemu-project/qemu.git'
        required: true
        options:
          - https://gitlab.com/qemu-project/qemu.git
          - git://git.infradead.org/qemu-nvme.git

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: registry login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            src=${{ github.event.inputs.upstream }}
            ref=${{ github.event.inputs.gitref }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.gitref }}
          labels: ${{ steps.meta.outputs.labels }}
